name: vcheck_flutter_example
description: Demonstrates how to use the vcheck_flutter plugin.

publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  vcheck_flutter:
    path: ../
    
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
